spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/movies_database"
    username: dio
    password: dio

  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: create
    show-sql: true
